# === FINETUNING CONFIG ===
experiment:
  name: __WILL_BE_FILLED__
  kind: finetuning
  output_dir: experiments/finetuning/__WILL_BE_FILLED__
  seed: 420

logging:
  use_wandb: true
  wandb:
    entity: praca-inzynierska
    project: text_classification
    run_name: __WILL_BE_FILLED__
  log_train_loss: true
  log_train_lr: true
  log_train_grad_norm: true
  log_eval_metrics: true
  csv_train_metrics_path: metrics/train/metrics.csv
  csv_eval_metrics_path: metrics/eval/metrics.csv

pretrained_experiment:
  name: __WILL_BE_FILLED__
  path: experiments/pretraining/__WILL_BE_FILLED__
  checkpoint: checkpoints/model.ckpt
  inherit:
    - architecture
    - tokenizer

tokenizer:
  wrapper_path: src/textclf_transformer/tokenizer/wordpiece_tokenizer_wrapper.py
  vocab_dir: src/textclf_transformer/tokenizer/BERT_original
  vocab_path: src/textclf_transformer/tokenizer/BERT_original/vocab.txt
  max_length: 1000

architecture:
  max_sequence_length: 1000
  embedding_dim: 32
  num_layers: 4
  mlp_size: 128
  mlp_dropout: 0.1
  pos_encoding: learned
  embedding_dropout: 0.1

  attention:
    num_heads: 4
    projection_bias: true # (Q/K/V/out) bias
    attn_out_dropout: 0.1 # dropout na projekcji wyjściowej
    attn_dropout: 0.0 # dropout na wagach atencji (po softmax)

    kind: lsh # 'mha' | 'lsh' | 'favor'
    ###attention_params###
    mha:
    lsh: 
      num_hashes: 4
      chunk_size: 64
    favor: 
      #TODO add params
    ###attention_forward_params###
    forward_mha:
    forward_lsh:
      mask_within_chunks: true
    forward_favor:

classification_head:
  num_labels: 2
  classifier_dropout: 0.1
  pooling: cls # 'cls' | 'mean' | 'max' | 'min'
  pooler_type: bert # 'bert' | 'roberta' | null

training:
  batch_size: 32
  epochs: 3
  learning_rate: 2.0e-5
  warmup_ratio: 0.1
  weight_decay: 0.01
  max_grad_norm: 1.0
  grad_accum_steps: 1
  use_amp: true
  loss: cross_entropy
  device: auto

data:
  train:
    dataset_path: data/tokenized/IMDB/train_dataset.pt
  val:
    dataset_path: data/tokenized/IMDB/val_dataset.pt
  test:
    dataset_path: data/tokenized/IMDB/test_dataset.pt
