# === PRETRAINING CONFIG ===
experiment:
  name: __WILL_BE_FILLED__
  kind: pretraining
  output_dir: experiments/pretraining/__WILL_BE_FILLED__
  seed: 420

logging:
  use_wandb: true
  wandb:
    entity: praca-inzynierska
    project: text_classification
    run_name: __WILL_BE_FILLED__
  log_train_loss: true
  log_train_lr: true
  log_train_grad_norm: true
  log_eval_metrics: true
  csv_train_metrics_path: metrics/train/metrics.csv
  csv_eval_metrics_path: metrics/eval/metrics.csv

tokenizer:
  wrapper_path: src/textclf_transformer/tokenizer/wordpiece_tokenizer_wrapper.py
  vocab_dir: src/textclf_transformer/tokenizer/BERT_original
  max_length: 1000

architecture:
  max_sequence_length: 1000
  embedding_dim: 32
  num_layers: 4
  mlp_size: 128
  mlp_dropout: 0.1
  pos_encoding: learned # 'learned' | 'sinusoidal'
  embedding_dropout: 0.1
  pad_token_id: 0

  attention:
    kind: mha # 'mha' | 'reformer' | 'performer'
    mha:
      num_heads: 4
      projection_bias: true # (Q/K/V/out) bias
      mha_out_dropout: 0.1 # dropout na projekcji wyjściowej MHSA
      attn_dropout: 0.0 # dropout na wagach atencji (po softmax)
    reformer: {}
    performer: {}

mlm_head:
  tie_mlm_weights: true
  mask_p: 0.15
  mask_token_p: 0.8
  random_token_p: 0.1

training:
  batch_size: 64
  epochs: 3
  learning_rate: 2.0e-4
  warmup_ratio: 0.1
  weight_decay: 0.01
  max_grad_norm: 1.0
  grad_accum_steps: 1
  use_amp: true
  loss: cross_entropy
  device: auto # 'gpu' | 'cpu' | 'auto'

data:
  train:
    dataset_path: data/tokenized/IMDB/train_dataset.pt
  val:
    dataset_path: data/tokenized/IMDB/val_dataset.pt
